/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManterTipoProduto.java
 *
 * Created on Sep 11, 2011, 11:47:01 AM
 */
package view;

import controller.ManterTipoProdutoController;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.TipoProduto;
import util.FixedLengthDocument;

/**
 *
 * @author Vitor Freitas
 */
public class FrmManterTipoProduto extends javax.swing.JDialog {
    private DefaultListModel model;

    /** Creates new form ManterTipoProduto */
    public FrmManterTipoProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        BufferedImage image = null;
        try {
            image = ImageIO.read(this.getClass().getResource("/images/ruby.png"));
        } catch (IOException e) {
            
        }
        this.setIconImage(image);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTipoProduto = new javax.swing.JPanel();
        lbTitleTipoProduto = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        lbDescricao = new javax.swing.JLabel();
        spTipoProduto = new javax.swing.JScrollPane();
        listTipoProduto = new javax.swing.JList();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipo de Produto");
        setResizable(false);

        pnTipoProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTitleTipoProduto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitleTipoProduto.setForeground(new java.awt.Color(51, 51, 51));
        lbTitleTipoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/process.png"))); // NOI18N
        lbTitleTipoProduto.setText("Tipo de Produto");

        lbCodigo.setText("Código:");

        txtCodigo.setDocument(new FixedLengthDocument(3));

        txtDescricao.setDocument(new FixedLengthDocument(100));

        lbDescricao.setText("Descrição:");

        model = new DefaultListModel();
        listTipoProduto.setModel(model);
        carregarLista();
        listTipoProduto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTipoProdutoValueChanged(evt);
            }
        });
        spTipoProduto.setViewportView(listTipoProduto);

        javax.swing.GroupLayout pnTipoProdutoLayout = new javax.swing.GroupLayout(pnTipoProduto);
        pnTipoProduto.setLayout(pnTipoProdutoLayout);
        pnTipoProdutoLayout.setHorizontalGroup(
            pnTipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTipoProdutoLayout.createSequentialGroup()
                .addGroup(pnTipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTipoProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnTipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDescricao)
                            .addComponent(lbCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
                    .addGroup(pnTipoProdutoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbTitleTipoProduto))
                    .addGroup(pnTipoProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spTipoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnTipoProdutoLayout.setVerticalGroup(
            pnTipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTipoProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitleTipoProduto)
                .addGap(18, 18, 18)
                .addGroup(pnTipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disk.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTipoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarLista(){
        model.clear();
        try {
            List<TipoProduto> tipoProdutos = new ArrayList<TipoProduto>();
            tipoProdutos = ManterTipoProdutoController.getInstance().getTipoProdutos();
            for (TipoProduto tp : tipoProdutos) 
                model.addElement(tp);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar lista de Tipo de Produto");
            }
    }
    private void limparFormulario(){
        txtCodigo.setEnabled(true);
        txtCodigo.setText(null);
        txtDescricao.setText(null);
        txtCodigo.requestFocus();
        listTipoProduto.clearSelection();        
    }
    
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limparFormulario();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void listTipoProdutoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTipoProdutoValueChanged
        if (!listTipoProduto.isSelectionEmpty()){
            TipoProduto tp = (TipoProduto) listTipoProduto.getSelectedValue();
            txtCodigo.setText(tp.getCodigo());
            txtDescricao.setText(tp.getDescricao());
            txtCodigo.setEnabled(false);
        }
    }//GEN-LAST:event_listTipoProdutoValueChanged

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (!listTipoProduto.isSelectionEmpty()){
            try {
                ManterTipoProdutoController.getInstance().delete((TipoProduto) model.remove(listTipoProduto.getSelectedIndex()));
                limparFormulario();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        TipoProduto tp = new TipoProduto();
        tp.setCodigo(txtCodigo.getText());
        tp.setDescricao(txtDescricao.getText());
        try {
            ManterTipoProdutoController.getInstance().save(tp);
            limparFormulario();
            carregarLista();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FrmManterTipoProduto dialog = new FrmManterTipoProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbTitleTipoProduto;
    private javax.swing.JList listTipoProduto;
    private javax.swing.JPanel pnTipoProduto;
    private javax.swing.JScrollPane spTipoProduto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
