/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmFornecedor.java
 *
 * Created on Sep 10, 2011, 3:31:12 PM
 */
package view;

import controller.ManterFornecedorController;
import java.awt.Component;
import java.sql.SQLException;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import model.Fornecedor;
import tablemodel.FornecedorTableModel;

/**
 *
 * @author Vitor Freitas
 */
public class FrmPanelFornecedor extends javax.swing.JPanel implements Observer {
    private FornecedorTableModel model;
    
    private static final ImageIcon ativo
        = new ImageIcon(FrmPanelFornecedor.class.getResource("/images/accept.png"));
    private static final ImageIcon inativo
        = new ImageIcon(FrmPanelFornecedor.class.getResource("/images/cross.png"));         
    
    /** Creates new form frmFornecedor */
    public FrmPanelFornecedor() {
        initComponents();
        ManterFornecedorController.getInstance().addObserver(this);
        tblFornecedores.getColumn("Status").setCellRenderer(createStatusColumnRenderer());
        tblFornecedores.setRowHeight(20);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitleFornecedor = new javax.swing.JLabel();
        spFornecedores = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        ckExibirTudo = new javax.swing.JCheckBox();

        lbTitleFornecedor.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbTitleFornecedor.setForeground(new java.awt.Color(51, 51, 51));
        lbTitleFornecedor.setText("Fornecedores");

        tblFornecedores.setModel(new FornecedorTableModel());
        addFornecedores();
        spFornecedores.setViewportView(tblFornecedores);

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        ckExibirTudo.setText("Exibir tudo");
        ckExibirTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckExibirTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spFornecedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addComponent(ckExibirTudo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitleFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitleFornecedor)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckExibirTudo))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addFornecedor(Fornecedor fornecedor) throws Exception{
        getModel().addFornecedor(fornecedor);
    }
    
    private void addFornecedores(){
        try{
            getModel().limpar();
            getModel().addListaDeFornecedores(ManterFornecedorController.getInstance().getFornecedores(ckExibirTudo.isSelected()));
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }   
    }
    
    private JTable getTblFornecedor() {
            if (tblFornecedores == null) {
                    tblFornecedores = new JTable();
                    tblFornecedores.setModel(new FornecedorTableModel());
            }
            return tblFornecedores;
    }

    private FornecedorTableModel getModel() {
            if (model == null) {
                    model = (FornecedorTableModel) getTblFornecedor().getModel();
            }
            return model;
    }   
    
    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        new FrmManterFornecedor(null, true, null).setVisible(true);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (tblFornecedores.getSelectedColumn()!=-1&&tblFornecedores.getSelectedRow()!=-1){
            Fornecedor fornecedor = new Fornecedor();
            fornecedor = (getModel().getFornecedor(tblFornecedores.getSelectedRow()));
            new FrmManterFornecedor(null, true, fornecedor).setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada.");
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblFornecedores.getSelectedColumn()!=-1&&tblFornecedores.getSelectedRow()!=-1){
            Fornecedor fornecedor = new Fornecedor();
            fornecedor = (getModel().getFornecedor(tblFornecedores.getSelectedRow()));
            if (JOptionPane.showConfirmDialog(null, "Confirmar exclusão do fornecedor "+fornecedor.getNomeFantasia()+"?")==0){
                try {
                    ManterFornecedorController.getInstance().delete(fornecedor);
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "Não é possível exlcuir um fornecedor com produtos relacionados.");
                } catch (ClassNotFoundException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada.");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void ckExibirTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckExibirTudoActionPerformed
        addFornecedores();
    }//GEN-LAST:event_ckExibirTudoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JCheckBox ckExibirTudo;
    private javax.swing.JLabel lbTitleFornecedor;
    private javax.swing.JScrollPane spFornecedores;
    private javax.swing.JTable tblFornecedores;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        addFornecedores();
        //if (arg!=null) JOptionPane.showMessageDialog(this, arg);
    }
    
    
    


    protected TableCellRenderer createStatusColumnRenderer() {
        return new StatusColumnRenderer();
    }
    
    protected static class StatusColumnRenderer extends DefaultTableCellRenderer {
            public Component getTableCellRendererComponent(JTable table,
                                                           Object value,
                                                           boolean isSelected,
                                                           boolean hasFocus,
                                                           int row,
                                                           int column) {

            super.getTableCellRendererComponent(table, value, isSelected,
                                                hasFocus, row, column);

            setText("");
            setHorizontalAlignment(SwingConstants.CENTER);

            /* set the icon based on the passed status */
            boolean status = (Boolean)value;
            setIcon(status ? ativo : inativo);

            return this;
        }
    }
    
}
