/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmProduto.java
 *
 * Created on Sep 10, 2011, 3:31:47 PM
 */
package view;

import controller.ManterFornecedorController;
import controller.ManterProdutoController;
import controller.ManterTipoProdutoController;
import java.awt.Component;
import java.sql.SQLException;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;
import model.Fornecedor;
import model.Produto;
import model.TipoProduto;
import util.Horus;
import tablemodel.ProdutoTableModel;

/**
 *
 * @author Vitor Freitas
 */
public class FrmPanelProduto extends javax.swing.JPanel implements Observer {
    private ProdutoTableModel model;
    private int limit;
    private int offset;
    private Integer numRegs;
    
    private static final ImageIcon ativo
        = new ImageIcon(FrmPanelProduto.class.getResource("/images/accept.png"));
    private static final ImageIcon inativo
        = new ImageIcon(FrmPanelProduto.class.getResource("/images/cross.png"));   
    
    private TableRowSorter<ProdutoTableModel> sorter;
    
    /** Creates new form frmProduto */
    public FrmPanelProduto() {
        initComponents();
        ManterTipoProdutoController.getInstance().addObserver(this);        
        ManterFornecedorController.getInstance().addObserver(this);
        ManterProdutoController.getInstance().addObserver(this);
        initPaginacao();
        
        tblProdutos.getColumn("Status").setCellRenderer(createStatusColumnRenderer());
        tblProdutos.setRowHeight(20);
        
        sorter = new TableRowSorter<ProdutoTableModel>(model);
        
        tblProdutos.setRowSorter(sorter);
    }
    
    private void initPaginacao(){
        limit = Horus.retornaNumRegs(cbPaginas.getSelectedItem());
        offset = 0;
        numRegs = ManterProdutoController.getInstance().countProdutos(getFiltro());
        lbTotalProdutos.setText(numRegs.toString());
        lbPaginaAtual.setText("1");
        lbTotalPaginas.setText(Horus.defineNumeroPaginas(numRegs, limit).toString());
        addProdutos();
        habilitaBotoes();
    }
    
    private void paginacao(Integer pag){
        lbPaginaAtual.setText(pag.toString());
        addProdutos();
    }
    
    private void habilitaBotoes(){
        btnVoltarTodos.setEnabled(!lbPaginaAtual.getText().equals("1"));
        btnVoltarUm.setEnabled(!lbPaginaAtual.getText().equals("1"));
        btnAvancarUm.setEnabled(!lbPaginaAtual.getText().equals(lbTotalPaginas.getText()));
        btnAvancarTodos.setEnabled(!lbPaginaAtual.getText().equals(lbTotalPaginas.getText()));
    }    
    
    private void addProduto(Produto produto) throws Exception{
        getModel().addProduto(produto);
    }
    
    private void addProdutos(){
        try{
            getModel().limpar();
            getModel().addListaDeProdutos(ManterProdutoController.getInstance().getProdutos(getFiltro(), limit, offset));
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    /*
    private void addProdutos(Produto filtro){
        try{
            getModel().limpar();
            getModel().addListaDeProdutos(ManterProdutoController.getInstance().getProdutos(filtro, limit, offset));
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }*/
    
    private JTable getTblProduto() {
            if (tblProdutos == null) {
                    tblProdutos = new JTable();
                    tblProdutos.setModel(new ProdutoTableModel());
            }
            return tblProdutos;
    }

    private ProdutoTableModel getModel() {
            if (model == null) {
                    model = (ProdutoTableModel) getTblProduto().getModel();
            }
            return model;
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitleProduto = new javax.swing.JLabel();
        pnFiltros = new javax.swing.JPanel();
        lbFiltroTipoProduto = new javax.swing.JLabel();
        cbTipoProduto = new javax.swing.JComboBox();
        lbFiltroFornecedor = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox();
        btnFiltrar = new javax.swing.JButton();
        btnExibirTudo = new javax.swing.JButton();
        lbFiltroStatus = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox();
        txtFiltro = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        spProdutos = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnVoltarTodos = new javax.swing.JButton();
        btnVoltarUm = new javax.swing.JButton();
        btnAvancarUm = new javax.swing.JButton();
        btnAvancarTodos = new javax.swing.JButton();
        lbTotalProdutos = new javax.swing.JLabel();
        lbDescricaoTotalProdutos = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        lbTotalPaginas = new javax.swing.JLabel();
        lbExibirRegistros1 = new javax.swing.JLabel();
        cbPaginas = new javax.swing.JComboBox();
        lbExibirRegistros2 = new javax.swing.JLabel();
        lbPagina2 = new javax.swing.JLabel();
        lbPaginaAtual = new javax.swing.JLabel();
        lbPagina1 = new javax.swing.JLabel();

        lbTitleProduto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitleProduto.setForeground(new java.awt.Color(51, 51, 51));
        lbTitleProduto.setText("Produtos");

        pnFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        lbFiltroTipoProduto.setText("Tipo de Produto");

        try {
            Horus.atualizarComboBox(cbTipoProduto, ManterTipoProdutoController.getInstance().getTipoProdutos());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao carregar Tipos de Produtos!");
        }

        lbFiltroFornecedor.setText("Fornecedor");

        try {
            Horus.atualizarComboBox(cbFornecedor, ManterFornecedorController.getInstance().getFornecedoresAtivos());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao carregar Fornecedores!");
        }

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/funnel.png"))); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnExibirTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/asterisk_orange.png"))); // NOI18N
        btnExibirTudo.setText("Exibir Tudo");
        btnExibirTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirTudoActionPerformed(evt);
            }
        });

        lbFiltroStatus.setText("Status");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Ativos", "Inativos" }));
        cbStatus.setSelectedIndex(1);

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnFiltrosLayout = new javax.swing.GroupLayout(pnFiltros);
        pnFiltros.setLayout(pnFiltrosLayout);
        pnFiltrosLayout.setHorizontalGroup(
            pnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFiltroTipoProduto))
                .addGap(18, 18, 18)
                .addGroup(pnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFiltroFornecedor)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFiltrosLayout.createSequentialGroup()
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExibirTudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrar))
                    .addComponent(lbFiltroStatus))
                .addContainerGap())
        );
        pnFiltrosLayout.setVerticalGroup(
            pnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFiltrosLayout.createSequentialGroup()
                .addGroup(pnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFiltroTipoProduto)
                    .addComponent(lbFiltroFornecedor)
                    .addComponent(lbFiltroStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar)
                    .addComponent(btnExibirTudo)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblProdutos.setModel(new ProdutoTableModel());
        tblProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProdutosKeyReleased(evt);
            }
        });
        spProdutos.setViewportView(tblProdutos);

        btnVoltarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backward.png"))); // NOI18N
        btnVoltarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarTodosActionPerformed(evt);
            }
        });

        btnVoltarUm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1308927345_Arrow-Left.png"))); // NOI18N
        btnVoltarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarUmActionPerformed(evt);
            }
        });

        btnAvancarUm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1308927338_Arrow-Right.png"))); // NOI18N
        btnAvancarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarUmActionPerformed(evt);
            }
        });

        btnAvancarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1308927319_Fast-Forward.png"))); // NOI18N
        btnAvancarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarTodosActionPerformed(evt);
            }
        });

        lbTotalProdutos.setText("0");

        lbDescricaoTotalProdutos.setText("Total de produtos:");

        lbTotalPaginas.setText("1");

        lbExibirRegistros1.setText("Exibir");

        cbPaginas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "25", "50", "100", "Todos" }));
        cbPaginas.setSelectedIndex(1);
        cbPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaginasActionPerformed(evt);
            }
        });

        lbExibirRegistros2.setText("registros por página");

        lbPagina2.setText("de");

        lbPaginaAtual.setText("1");

        lbPagina1.setText("Página");

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbExibirRegistros1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbExibirRegistros2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addComponent(lbPagina1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPaginaAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPagina2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotalPaginas)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalPaginas)
                    .addComponent(lbExibirRegistros1)
                    .addComponent(cbPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbExibirRegistros2)
                    .addComponent(lbPagina2)
                    .addComponent(lbPaginaAtual)
                    .addComponent(lbPagina1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spProdutos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addComponent(pnFiltros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lbTitleProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluir))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnVoltarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltarUm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAvancarUm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAvancarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                        .addComponent(lbDescricaoTotalProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalProdutos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitleProduto)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVoltarTodos)
                        .addComponent(btnVoltarUm)
                        .addComponent(btnAvancarUm)
                        .addComponent(btnAvancarTodos))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTotalProdutos)
                        .addComponent(lbDescricaoTotalProdutos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        new FrmManterProduto(null,true,null).setVisible(true);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (tblProdutos.getSelectedColumn()!=-1&&tblProdutos.getSelectedRow()!=-1){
            int modelRow = tblProdutos.convertRowIndexToModel(tblProdutos.getSelectedRow());
            Produto produto = new Produto();
            produto = (getModel().getProduto(modelRow));
            new FrmManterProduto(null, true, produto).setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada.");
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExibirTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirTudoActionPerformed
        cbFornecedor.setSelectedIndex(-1);
        cbTipoProduto.setSelectedIndex(-1);
        cbStatus.setSelectedIndex(0);
        initPaginacao();
    }//GEN-LAST:event_btnExibirTudoActionPerformed

    private Produto getFiltro(){
        Produto filtro = new Produto();
        Integer status = null;
        
        if (cbFornecedor.getSelectedIndex()!=-1)
            filtro.setFornecedor((Fornecedor) cbFornecedor.getSelectedItem());
        if (cbTipoProduto.getSelectedIndex()!=-1)
            filtro.setTipoProduto((TipoProduto) cbTipoProduto.getSelectedItem());
        if (cbStatus.getSelectedIndex()==1)
            status = 1;
        else if (cbStatus.getSelectedIndex()==2)
            status = 0;
        filtro.setIcAtivo(status);
        return filtro;
    }
    
    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        //addProdutos();
        initPaginacao();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnAvancarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarUmActionPerformed
        offset = offset + limit;
        paginacao(Integer.parseInt(lbPaginaAtual.getText())+1);
        habilitaBotoes();
    }//GEN-LAST:event_btnAvancarUmActionPerformed

    private void btnVoltarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTodosActionPerformed
        offset = 0;
        paginacao(1);
        habilitaBotoes();
    }//GEN-LAST:event_btnVoltarTodosActionPerformed

    private void btnVoltarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarUmActionPerformed
        offset = offset - limit;
        paginacao(Integer.parseInt(lbPaginaAtual.getText())-1);
        habilitaBotoes();
    }//GEN-LAST:event_btnVoltarUmActionPerformed

    private void btnAvancarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarTodosActionPerformed
        offset = (Integer.parseInt(lbTotalPaginas.getText())*limit)-limit;
        paginacao(Integer.parseInt(lbTotalPaginas.getText()));
        habilitaBotoes();
    }//GEN-LAST:event_btnAvancarTodosActionPerformed

    private void cbPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaginasActionPerformed
        initPaginacao();
    }//GEN-LAST:event_cbPaginasActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblProdutos.getSelectedColumn()!=-1&&tblProdutos.getSelectedRow()!=-1){
            int modelRow = tblProdutos.convertRowIndexToModel(tblProdutos.getSelectedRow());
            Produto produto = new Produto();
            produto = (getModel().getProduto(modelRow));
            if (JOptionPane.showConfirmDialog(null, "Confirmar exclusão do produto "+produto.getNome()+"?")==JOptionPane.YES_OPTION){
                try {
                    ManterProdutoController.getInstance().delete(produto);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Não é possível excluir um produto em estoque ou associado a um mostruário.");  
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada.");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        if (cbPaginas.getSelectedIndex()!=4)
            cbPaginas.setSelectedIndex(4);
        
        String text = txtFiltro.getText();
        if (text.length() == 0) {
          sorter.setRowFilter(null);
        } else {
          sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text));
        }
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void tblProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProdutosKeyReleased
        if (evt.getKeyCode()==122){
            if (tblProdutos.getSelectedColumn()!=-1&&tblProdutos.getSelectedRow()!=-1){
                int modelRow = tblProdutos.convertRowIndexToModel(tblProdutos.getSelectedRow());
                Produto produto = new Produto();
                produto = (getModel().getProduto(modelRow));
                ImagemDialog imagemDialog = new ImagemDialog(null, true, produto.getCodigo());
                imagemDialog.setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada.");
            }
        }
    }//GEN-LAST:event_tblProdutosKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAvancarTodos;
    private javax.swing.JButton btnAvancarUm;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExibirTudo;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnVoltarTodos;
    private javax.swing.JButton btnVoltarUm;
    private javax.swing.JComboBox cbFornecedor;
    private javax.swing.JComboBox cbPaginas;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JComboBox cbTipoProduto;
    private javax.swing.JLabel lbDescricaoTotalProdutos;
    private javax.swing.JLabel lbExibirRegistros1;
    private javax.swing.JLabel lbExibirRegistros2;
    private javax.swing.JLabel lbFiltroFornecedor;
    private javax.swing.JLabel lbFiltroStatus;
    private javax.swing.JLabel lbFiltroTipoProduto;
    private javax.swing.JLabel lbPagina1;
    private javax.swing.JLabel lbPagina2;
    private javax.swing.JLabel lbPaginaAtual;
    private javax.swing.JLabel lbTitleProduto;
    private javax.swing.JLabel lbTotalPaginas;
    private javax.swing.JLabel lbTotalProdutos;
    private javax.swing.JPanel pnFiltros;
    private javax.swing.JScrollPane spProdutos;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        try {
            if (o instanceof ManterFornecedorController) 
                Horus.atualizarComboBox(cbFornecedor, ManterFornecedorController.getInstance().getFornecedoresAtivos());
            
            if (o instanceof ManterTipoProdutoController) 
                Horus.atualizarComboBox(cbTipoProduto, ManterTipoProdutoController.getInstance().getTipoProdutos());
            
           // if (o instanceof ManterProdutoController) 
                initPaginacao();
            //else 
              //  addProdutos();
            
        } catch (Exception e){
            
        }        
    }
    
    protected TableCellRenderer createStatusColumnRenderer() {
        return new StatusColumnRenderer();
    }
    
    protected static class StatusColumnRenderer extends DefaultTableCellRenderer {
            public Component getTableCellRendererComponent(JTable table,
                                                           Object value,
                                                           boolean isSelected,
                                                           boolean hasFocus,
                                                           int row,
                                                           int column) {

            super.getTableCellRendererComponent(table, value, isSelected,
                                                hasFocus, row, column);

            setText("");
            setHorizontalAlignment(SwingConstants.CENTER);

            /* set the icon based on the passed status */
            boolean status = (Boolean)value;
            setIcon(status ? ativo : inativo);

            return this;
        }
    }    
}
