/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmRevendedora.java
 *
 * Created on Sep 10, 2011, 3:32:08 PM
 */
package view;

import controller.ManterRevendedoraController;
import java.awt.Component;
import java.sql.SQLException;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import model.Revendedora;
import tablemodel.RevendedoraTableModel;

/**
 *
 * @author Vitor Freitas
 */
public class FrmPanelRevendedora extends javax.swing.JPanel implements Observer{
    private RevendedoraTableModel model;
    
    private static final ImageIcon ativo
        = new ImageIcon(FrmPanelRevendedora.class.getResource("/images/accept.png"));
    private static final ImageIcon inativo
        = new ImageIcon(FrmPanelRevendedora.class.getResource("/images/cross.png"));     

    /** Creates new form frmRevendedora */
    public FrmPanelRevendedora() {
        initComponents();
        ManterRevendedoraController.getInstance().addObserver(this);
        tblRevendedoras.getColumn("Status").setCellRenderer(createStatusColumnRenderer());
        tblRevendedoras.setRowHeight(20);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitleRevendedora = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        spRevendedoras = new javax.swing.JScrollPane();
        tblRevendedoras = new javax.swing.JTable();
        ckExibirTudo = new javax.swing.JCheckBox();

        lbTitleRevendedora.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbTitleRevendedora.setForeground(new java.awt.Color(51, 51, 51));
        lbTitleRevendedora.setText("Revendedoras");

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblRevendedoras.setModel(new RevendedoraTableModel());
        addRevendedoras();
        spRevendedoras.setViewportView(tblRevendedoras);

        ckExibirTudo.setText("Exibir tudo");
        ckExibirTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckExibirTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spRevendedoras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addComponent(ckExibirTudo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitleRevendedora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitleRevendedora)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spRevendedoras, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckExibirTudo))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addRevendedora(Revendedora revendedora) throws Exception{
        getModel().addRevendedora(revendedora);
    }
    
    private void addRevendedoras(){
        try{
            getModel().limpar();
            getModel().addListaDeRevendedoras(ManterRevendedoraController.getInstance().getRevendedoras(ckExibirTudo.isSelected()));
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    
    private JTable getTblRevendedora() {
            if (tblRevendedoras == null) {
                    tblRevendedoras = new JTable();
                    tblRevendedoras.setModel(new RevendedoraTableModel());
            }
            return tblRevendedoras;
    }

    private RevendedoraTableModel getModel() {
            if (model == null) {
                    model = (RevendedoraTableModel) getTblRevendedora().getModel();
            }
            return model;
    }   
    
    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        FrmManterRevendedora frmManterRevendedora = new FrmManterRevendedora(null, true, null);
        frmManterRevendedora.setVisible(true);
        /*if (frmManterRevendedora.atualizaLista()){
            addRevendedoras();
            JOptionPane.showMessageDialog(null, "Revendedora incluída com sucesso!");
        }
         * 
         */
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (tblRevendedoras.getSelectedColumn()!=-1&&tblRevendedoras.getSelectedRow()!=-1){
            Revendedora revendedora = new Revendedora();
            revendedora = (getModel().getRevendedora(tblRevendedoras.getSelectedRow()));
            new FrmManterRevendedora(null, true, revendedora).setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada.");
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblRevendedoras.getSelectedColumn()!=-1&&tblRevendedoras.getSelectedRow()!=-1){
            Revendedora revendedora = new Revendedora();
            revendedora = (getModel().getRevendedora(tblRevendedoras.getSelectedRow()));
            if (JOptionPane.showConfirmDialog(null, "Confirmar exclusão da revendedora "+revendedora.getNome()+"?")==0){
                try {
                    ManterRevendedoraController.getInstance().delete(revendedora);
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "Não é possível excluir uma revendedora com mostruários relacionados.");  
                } catch (ClassNotFoundException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada.");        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void ckExibirTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckExibirTudoActionPerformed
        addRevendedoras();
    }//GEN-LAST:event_ckExibirTudoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JCheckBox ckExibirTudo;
    private javax.swing.JLabel lbTitleRevendedora;
    private javax.swing.JScrollPane spRevendedoras;
    private javax.swing.JTable tblRevendedoras;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        addRevendedoras();
    }
    
    
    
    protected TableCellRenderer createStatusColumnRenderer() {
        return new StatusColumnRenderer();
    }
    
    protected static class StatusColumnRenderer extends DefaultTableCellRenderer {
            public Component getTableCellRendererComponent(JTable table,
                                                           Object value,
                                                           boolean isSelected,
                                                           boolean hasFocus,
                                                           int row,
                                                           int column) {

            super.getTableCellRendererComponent(table, value, isSelected,
                                                hasFocus, row, column);

            setText("");
            setHorizontalAlignment(SwingConstants.CENTER);

            /* set the icon based on the passed status */
            boolean status = (Boolean)value;
            setIcon(status ? ativo : inativo);

            return this;
        }
    }
    
}
